name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Deploy project to CDN
        run: rsync --rsh="/usr/bin/sshpass -p "PHLkcFKA}q5K" ssh -o StrictHostKeyChecking=no -l root" ./* test@173.230.147.195:/home/test/

